#!/bin/bash

# Source environment variables for parsec scripts
source ../../../env.sh

# Run scripts in sbatch
sbatch ./scalability_openmp_1
sbatch ./scalability_openmp_2
sbatch ./scalability_openmp_4
sbatch ./scalability_openmp_8
sbatch ./scalability_openmp_16
sbatch ./scalability_openmp_32
