#!/bin/bash
#SBATCH --job-name=fluidanimate_scalability_openmp
#SBATCH --time=0-0:15
#SBATCH --cpus-per-task=2
#SBATCH --hint=compute_bound
#SBATCH --mail-user=cadubentzen@gmail.com
#SBATCH --mail-type=ALL

for i in 1 2 3
do
	parsecmgmt -a run -p parsec.fluidanimate -c gcc-openmp -i simlarge -n 2
	parsecmgmt -a run -p parsec.fluidanimate -c gcc-openmp -i native -n 2
done
